### ISSUE TITLE
ELVIS Project Front Page

### ISSUE THREAD

**Issue by musicus** [ELVIS-Project/elvisproject#3]
When selecting "COUNTERPOINT WEB APP" from the slider menu, and then clicking on the "Start the app >>" link under "FIND REPEATED PATTERNS", the user is directed to http://counterpoint.elvisproject.ca, which generates a 500 internal server error. Either disable the link with an explanation, as a temporary fix, or remove the "COUNTERPOINT WEB APP" slide.

**Comment by crantila** [comment]
... or find out wth happened to the CWA?

**Comment by mrbannon** [comment]
I'm looking at it right now. No idea why this is down...never touched it.

**Comment by crantila** [comment]
Answer: someone set HTTPD to run with a custom-installed Python 3 for the ELVIS Database. The Counterpoint Web App is a Python 2 program.

**Comment by ahankinson** [comment]
That would be @lexpar.

**Comment by crantila** [comment]
If nobody's using the `cwa-devel` VM for testing, we could just have it serve the CWA proper?

**Comment by crantila** [comment]
Is there a reason to use a custom-installed Python 3, btw? Rather than the one in the repository?

**Comment by ahankinson** [comment]
Not sure.

**Comment by mrbannon** [comment]
This is fine with me. I think AlexP will have to be tasked with this. :)

**Comment by mrbannon** [comment]
Christopher, do you mind if I have Alex P. coordinate with you on this? He
might need some help.

**Comment by agpar** [comment]
I updated ElvisDB to Python3 during the last week of the summer... Did not realize that this was broken.

There has been almost no development on ElvisDB since this switch. I can just rollback to the python 2 version and get httpd on the py2 wsgi again. That would be quick.

**Comment by mrbannon** [comment]
That would be great!

**Comment by ahankinson** [comment]
Can't we virtualenv it?

Did you install Python 3 with `yum` or did you compile it yourself (Christopher's note about "custom built" python seems to suggest that you may have?)

**Comment by agpar** [comment]
The latter.

**Comment by crantila** [comment]
Rolling back to Py2 seems like the best solution, then. I'm 100% in favour of Python 3 in general, but since the CWA will be phased out once vis-client works, there's no particular reason to port it to Python 3.

Speedy resolution. Thanks for your help, everyone!

**Comment by ahankinson** [comment]
So:
- yum install python3
- set up a virtualenv with py3 for the Elvis DB

This page might help:
http://thecodeship.com/deployment/deploy-django-apache-virtualenv-and-mod_wsgi/

**Comment by agpar** [comment]
Can the apache server run py3 and py2 versions of mod_wsgi at the same time?

**Comment by mrbannon** [comment]
Indeed, thanks!

**Comment by crantila** [comment]
I don't even know how you got Apache to run Python 3 in the first place...

**Comment by crantila** [comment]
NB the package name is "python34" because, well, why not...

**Comment by agpar** [comment]
You can compile the mod_wsgi module for the apache server using whichever python version you want to support. It doesn't look like you can have two versions of mod_wsgi running on the same server though.

**Comment by agpar** [comment]
And I should mention that I have no idea why I installed py3 from source on the server... I'm sure it made sense at the time.

**Comment by crantila** [comment]
... you re-compiled `mod_wsgi` too?! Nobody can say you don't work hard!

**Comment by agpar** [comment]
I was blinded by py3-lust.

**Comment by ahankinson** [comment]
```
$> pip install py3-lust
Collecting py3-lust
  Could not find a version that satisfies the requirement py3-lust (from versions: )
No matching distribution found for py3-lust
```

**Comment by crantila** [comment]
But did you ever `import antigravity`?

**Comment by agpar** [comment]
Hmmm... It looks like I've drastically misremembered how much I've changed since moving to python 3.

**Bad News**: I've done a couple migrations since then that were consolidation/organization focused... A lot of fields have been moved and renamed.
**Good News**: I have a backup of the DB from 4 days before switching to py3.
**Bad News**: Rolling back means losing all progress I've made and any pieces that have been created since then.
**Good(?) News**: Only 4 pieces have been created since then.

So - if this still appears to be the easiest option then I can attempt a roll back, but it won't be nearly as quick as I hoped.

**Comment by ahankinson** [comment]
Please don't roll back to Py2.

The CWA is set to be deprecated in the near future. If it's too difficult to host them both on the same machine, we can move it to another server in the interim.

**Comment by agpar** [comment]
_Alex sighs in relief._

**Comment by crantila** [comment]
Oh... this means someone should probably change the DNS configuration, and the `cwa-devel` host's HTTPD configuration, right.

@ahankinson if you can adjust the DNS so that `counterpoint.elvisproject.ca` points to 132.206.14.132 then I can reconfigure HTTPD. Is this okay, or am I missing something?

**Comment by ahankinson** [comment]
Done. It should take effect soon.

**Comment by crantila** [comment]
Thanks for the speedy service, Andrew!

I've updated and restarted the VM, and changed the HTTPD configuration. It's still using VIS `2.0.py3-continuousLily-4`, pandas 0.15.2, and music21 1.9.3. I don't think upgrading those libraries will have any positive effect, since this VIS version offers a couple of niche features that weren't available on the "deployment" server (notably "continuous LilyPond output").

I'm closing this issue, but if anyone has further questions or something bad happens, please feel free to re-open it. Special thanks to @musicus for noticing and opening the issue, and to @lexpar for his investigative work!
